version: 2
updates:
  # Configuração para dependências Rust
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    reviewers:
      - "keyai-maintainers"
    labels:
      - "dependencies"
      - "rust"
      - "automated"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    allow:
      - dependency-type: "all"
    ignore:
      # Ignorar atualizações major de certas dependências críticas
      - dependency-name: "tauri"
        update-types: ["version-update:semver-major"]
      - dependency-name: "tokio"
        update-types: ["version-update:semver-major"]
    groups:
      rust-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Configuração para dependências npm (frontend)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    reviewers:
      - "keyai-maintainers"
    labels:
      - "dependencies"
      - "javascript"
      - "automated"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    allow:
      - dependency-type: "all"
    ignore:
      # Ignorar atualizações major de frameworks principais
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@tauri-apps/*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
    groups:
      npm-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      npm-dev:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  # Configuração para GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 3
    reviewers:
      - "keyai-maintainers"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "ci"
      include: "scope"

# Configurações de segurança do Dependabot
registries:
  # Se usar registros privados no futuro, configurar aqui

# Configuração de auto-merge (requer app Dependabot)
# auto-merge:
#   - match:
#       dependency-type: "development"
#       update-type: "semver-patch"
#   - match:
#       dependency-type: "production"
#       update-type: "semver-patch"