name: Auto Fix

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
    inputs:
      fix_type:
        description: 'Tipo de correção'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - format
          - clippy
          - dependencies
          - security

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  # Auto-fix ativado por comentário
  comment-trigger:
    name: Comment Trigger
    if: |
      github.event_name == 'issue_comment' && 
      github.event.issue.pull_request && 
      contains(github.event.comment.body, '/autofix')
    runs-on: ubuntu-latest
    steps:
      - name: Check permissions
        uses: actions/github-script@v7
        with:
          script: |
            const { data: permission } = await github.rest.repos.getCollaboratorPermissionLevel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              username: context.actor
            });
            
            if (!['admin', 'write'].includes(permission.permission)) {
              await github.rest.reactions.createForIssueComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: context.payload.comment.id,
                content: '-1'
              });
              throw new Error('Insufficient permissions');
            }
            
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: 'rocket'
            });

  # Formatação automática
  auto-format:
    name: Auto Format Code
    if: |
      github.event_name == 'pull_request' || 
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/autofix')) ||
      (github.event_name == 'workflow_dispatch' && contains(github.event.inputs.fix_type, 'all|format'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Format Rust code
        run: |
          cargo fmt --all
          echo "✅ Código Rust formatado" >> format_log.txt
      
      - name: Format Frontend code
        run: |
          cd frontend
          npm ci
          npx prettier --write "src/**/*.{ts,tsx,js,jsx,css}" || true
          echo "✅ Código Frontend formatado" >> ../format_log.txt
      
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          if git diff --staged --quiet; then
            echo "Nenhuma mudança de formatação necessária"
          else
            git commit -m "style: auto-format code 🎨"
            git push
          fi

  # Correções do Clippy
  auto-clippy-fix:
    name: Auto Fix Clippy Warnings
    if: |
      github.event_name == 'pull_request' || 
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/autofix')) ||
      (github.event_name == 'workflow_dispatch' && contains(github.event.inputs.fix_type, 'all|clippy'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev libxdo-dev
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      
      - name: Apply Clippy fixes
        run: |
          cargo clippy --fix --allow-dirty --allow-staged || true
          echo "✅ Correções do Clippy aplicadas" >> clippy_log.txt
      
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          if git diff --staged --quiet; then
            echo "Nenhuma correção do Clippy necessária"
          else
            git commit -m "fix: apply clippy suggestions 🔧"
            git push
          fi

  # Atualização de dependências
  auto-update-deps:
    name: Auto Update Dependencies
    if: |
      (github.event_name == 'workflow_dispatch' && contains(github.event.inputs.fix_type, 'all|dependencies')) ||
      github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Update Rust dependencies
        run: |
          cargo update
          echo "✅ Dependências Rust atualizadas" >> deps_log.txt
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Update npm dependencies
        run: |
          cd frontend
          npm update
          npm audit fix || true
          echo "✅ Dependências npm atualizadas" >> ../deps_log.txt
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies 📦'
          title: 'chore: atualização automática de dependências'
          body: |
            ## 📦 Atualização Automática de Dependências
            
            Este PR foi criado automaticamente para atualizar as dependências do projeto.
            
            ### Alterações:
            - Dependências Rust atualizadas via `cargo update`
            - Dependências npm atualizadas via `npm update`
            - Vulnerabilidades corrigidas via `npm audit fix`
            
            ### Checklist:
            - [ ] Testes passando
            - [ ] Build funcionando
            - [ ] Sem breaking changes
          branch: auto-update-dependencies
          delete-branch: true

  # Correções de segurança
  auto-security-fix:
    name: Auto Security Fixes
    if: |
      (github.event_name == 'workflow_dispatch' && contains(github.event.inputs.fix_type, 'all|security'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run security fixes
        run: |
          # Rust security
          cargo install cargo-audit || true
          cargo audit fix || true
          
          # NPM security
          cd frontend
          npm audit fix --force || true
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'security: auto-fix vulnerabilities 🔒'
          title: 'security: correções automáticas de segurança'
          body: |
            ## 🔒 Correções Automáticas de Segurança
            
            Este PR foi criado automaticamente para corrigir vulnerabilidades de segurança.
            
            ### Ações realizadas:
            - `cargo audit fix` para dependências Rust
            - `npm audit fix --force` para dependências npm
            
            ⚠️ **ATENÇÃO**: Revise cuidadosamente as mudanças antes de fazer merge.
          branch: auto-security-fixes
          delete-branch: true

  # Correção de erros comuns
  auto-common-fixes:
    name: Auto Common Fixes
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
      
      - name: Fix common issues
        run: |
          # Remover trailing whitespace
          find . -type f \( -name "*.rs" -o -name "*.ts" -o -name "*.tsx" \) -exec sed -i 's/[[:space:]]*$//' {} \;
          
          # Adicionar newline no final dos arquivos
          find . -type f \( -name "*.rs" -o -name "*.ts" -o -name "*.tsx" \) -exec sh -c 'tail -c1 {} | read -r _ || echo >> {}' \;
          
          # Corrigir imports não utilizados em Rust
          cargo fix --allow-dirty --allow-staged || true
          
          echo "✅ Correções comuns aplicadas" >> common_fixes_log.txt
      
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          if git diff --staged --quiet; then
            echo "Nenhuma correção comum necessária"
          else
            git commit -m "fix: apply common fixes 🛠️"
            git push
          fi